### PR TITLE
fix: reduce Prometheus scrape_interval to work with Kong Prometheus plugin 

### PR DESCRIPTION
**Pull request by devadvocado**
### Summary

Update the Prometheus scrape_interval to 10s to support the Kong Gateway Prometheus plugin. Scrape interval for the Kong gateway Prometheus proxy doesn't work well if the intervals are too far apart, so the easiest fix is to just lower the interval. Default Prometheus setting for the interval is 15s so no reason to have it at set to 1 minute to begin with.

### CODE REVIEW

**Comment by jakubdyszkiewicz** [comment]
I need more context. Why does this change fix stuff?

**Comment by devadvocado** [comment]
Updated the PR summary with explanation.

**Comment by jakubdyszkiewicz** [comment]
I think 1m was the default value from prometheus helm chart.
I think 10s might be a bit too often for a fleet of Envoys, but I'm ok with this PR since this is not hardcoded but can be reconfigured after deployment.

Please add a changelog

**Comment by jakubdyszkiewicz** [comment]
Please rebase to master @devadvocado to fix the CI

**Comment by devadvocado** [comment]
rebased onto master to resolve conflict on CHANGELOG file

**Pull request merged**
