### PR TITLE
docs: add proposal for collecting Prometheus metrics out of Envoys

### PR DESCRIPTION
**Pull request by yskopets**
### Summary

* add proposal for collecting `Prometheus` metrics out of `Envoys`

### CODE REVIEW

**Comment by subnetmarco** [comment]
@yskopets LGTM.

**Comment by yskopets** [comment]
@subnetmarco Added a section about per-`Dataplane` overrides on Kubernetes

**Comment by subnetmarco** [comment]
I like `prometheus.metrics.kuma.io/port` better because it can be scaled better for other use-cases as well.

> It is assumed, there will be no mTLS between Prometheus and the metrics endpoint exposed by a dataplane (`Envoy`)

Why are we making this assumption, can the Admin API port be protected via mTLS?

**Comment by yskopets** [comment]
@subnetmarco 

> Why are we making this assumption, can the Admin API port be protected via mTLS?

If the metrics endpoint was secured with mTLS, Prometheus would need to have a mTLS certificate like regular dataplanes.

Which is not easy from operations perspective since Prometheus is not part of a Service Mesh.

The hard part is rotating mTLS certificate.

Nothing in this design proposal prevents from adding support for mTLS in the future.

But it's left out of scope for the initial implementation.

**Comment by jakubdyszkiewicz** [comment]
Looks good!

From what I've seen, exposing all the metrics when every Envoy knows about any other cluster (K8S case) is too hard to maintain because there are too many metrics, so eventually we probably would want to add filtering, but this can be as easy as
```yaml
type: Mesh
name: default
mtls:
  ...
metrics:
  exclude:
  - metric1
  - metric2
  prometheus:
    port: 5670
    path: /metrics
```

**Comment by yskopets** [comment]
> From what I've seen, exposing all the metrics when every Envoy knows about any other cluster (K8S case) is too hard to maintain because there are too many metrics, so eventually we probably would want to add filtering, but this can be as easy as
> 
> ```yaml
> type: Mesh
> name: default
> mtls:
>   ...
> metrics:
>   exclude:
>   - metric1
>   - metric2
>   prometheus:
>     port: 5670
>     path: /metrics
> ```

Personally, I don't think that hiding metrics is a solution.

@subnetmarco Should we include this feature into current proposal ?

**Comment by subnetmarco** [comment]
It’s okay to not implement this in the first version, as long as the specification can be extended to handle this and other use-cases over time.

**Pull request merged**
