### PR TITLE
feat: limit number subscription

### PR DESCRIPTION
**Pull request by lobkovilya**
### Summary

Today we don't limit the number of subscriptions that could be stored in DataplaneInsight and there is no way to disable it. 
This PR introduces the ability to configure that functionality. 
Here is new config section:

```json
"metrics": {
  "dataplane": {
     "enabled": true,
     "subscriptionLimit": 10
  }
}
```

Note: `Enable` flag works quite naive and straightforward - it doesn't prevent `dataplaneInsightSink` from Start, just cut off all subscriptions before adding them to storage. That was the simplest way to implement, but if needed I can provide full fair `Enable` support

### CODE REVIEW

**Comment by subnetmarco** [comment]
@lobkovilya why as a user would I want to use this and where we document this setting?

**Comment by lobkovilya** [comment]
@subnetmarco I documented it here: https://github.com/Kong/kuma/pull/747/files#diff-67cae1b084c762f7b6f9ce54fcad8059R223, if I understand correctly we keep all config documentation right in that file.

We need somehow remove old subscriptions as @jakubdyszkiewicz proposed here https://github.com/Kong/kuma/issues/717. And it might be unobvious to have some hardcoded number like 10 and always leave only the last 10 subscriptions. Generally speaking, subscriptions are like logs or metrics, we should let the user decide how many of them he wants to store.

**Comment by subnetmarco** [comment]
What changes if the user decides to support more or less subscriptions? Basically, why would the user want to have more or less and what value he gets by having more?

**Comment by lobkovilya** [comment]
Since we store Subscriptions as an array (not just the latest subscription) then I assume there is some value in having more than 1 subscription. I guess it gives the user an ability to check the history of dp and cp reconnections. 
So if we agree that it makes sense to store more than 1 subscription then we should consider limiting the number of subscriptions. Probably we shouldn't give the user an ability to configure that limit (hardcoded value would be also fine)

**Pull request merged**
