### PR TITLE
feat(kuma-cp) extend clusters configuration with LBConfig

### PR DESCRIPTION
**Pull request by nickolaev**
### Summary

Add LBConfig with address for usage with Global CP. The purpose is to have a configurable address which Global CP can send to Remote CPs when initiating the XDS synchronization. Remote CPs will use this address to access the Global CP service back.

### CODE REVIEW

**Comment by nickolaev** [comment]
@lobkovilya that's pretty simple. Do we need a PR?

**Comment by lobkovilya** [comment]
Could you please also update `kuma-cp.defaults.yaml`. 
Sorry, not sure that I get you here, what do you mean "Do we need a PR?"?

**Comment by nickolaev** [comment]
Defaults are empty, so the yaml has no changes.
My question was do we even need this PR, it's a couple lines.

**Comment by nickolaev** [comment]
Adopted in #857

**Pull request closed without merging**
