### PR TITLE
feat(kumacp) included traffic direction in access log

### LINKED ISSUE #598: Introduce a `%KUMA_TRAFFIC_DIRECTION%` command operator into access log format to allow users to distinguish between access logs collected on source side vs destination side
### Summary

* Introduce a `%KUMA_TRAFFIC_DIRECTION%` command operator into access log format to allow users to distinguish between access logs collected on source side vs destination side

### PR DESCRIPTION
**Pull request by tharun208**
### Summary

Included `trafficDirection` in the access log.

### Full changelog

1. defaultHttpAccessLogFormat
2. defaultNetworkAccessLogFormat

### Issues resolved

Fix #598

### CODE REVIEW

**Comment by subnetmarco** [comment]
Thanks @tharun208 - Let us review this.

**Comment by tharun208** [comment]
> I'd omit to place it in the default configuration. We always put the logging on outbound at the moment.
should I need to remove 


> I'd omit placing it in the default configuration. We always put the logging on outbound at the moment.

I am not getting you on this. Can you explain a bit more, please?

**Comment by jakubdyszkiewicz** [comment]
`%KUMA_TRAFFIC_DIRECTION%` indicates whether the traffic that we are logging is incoming or outgoing. The thing is that right now we only log outgoing traffic (placing logging filter in outbound listeners), therefore, I don't think this information is that usefull that we have to put it in the default format.

**Comment by tharun208** [comment]
> `%KUMA_TRAFFIC_DIRECTION%` indicates whether the traffic that we are logging is incoming or outgoing. The thing is that right now we only log outgoing traffic (placing logging filter in outbound listeners), therefore, I don't think this information is that useful that we have to put it in the default format.

yes! agreed, within our outbound and inbound listeners we are showing traffic direction, can i close this PR ?

**Comment by jakubdyszkiewicz** [comment]
This functionality itself might be useful in the future. Just don't add it to `defaultHttpAccessLogFormat` and `defaultNetworkAccessLogFormat`.

**Comment by tharun208** [comment]
> This functionality itself might be useful in the future. Just don't add it to `defaultHttpAccessLogFormat` and `defaultNetworkAccessLogFormat`.

should we need this to be added to all the `configurer` within kuma?

**Comment by jakubdyszkiewicz** [comment]
> should we need this to be added to all the configurer within kuma?

I'm sorry, I don't think I get the question.
Everything about this PR is fine except change in default formats.

**Comment by tharun208** [comment]
> > should we need this to be added to all the configurer within kuma?
> 
> I'm sorry, I don't think I get the question.
> Everything about this PR is fine except change in default formats.

should I need to change it to `Kuma direction` to `UNSPECIFIED`?

**Comment by jakubdyszkiewicz** [comment]
No, but this code
```
const defaultHttpAccessLogFormat = `[%START_TIME%] %KUMA_MESH% "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%KUMA_SOURCE_SERVICE%" "%KUMA_DESTINATION_SERVICE%" "%KUMA_SOURCE_ADDRESS_WITHOUT_PORT%" "%UPSTREAM_HOST%"	

const defaultNetworkAccessLogFormat = `[%START_TIME%] %RESPONSE_FLAGS% %KUMA_MESH% %KUMA_SOURCE_ADDRESS_WITHOUT_PORT%(%KUMA_SOURCE_SERVICE%)->%UPSTREAM_HOST%(%KUMA_DESTINATION_SERVICE%) took %DURATION%ms, sent %BYTES_SENT% bytes, received: %BYTES_RECEIVED% bytes	
```
should stay as is.

**Comment by jakubdyszkiewicz** [comment]
thanks!

**Pull request merged**
